/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeDemoRouteImport } from './routes/home-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as LoginCheckPermissionRouteImport } from './routes/login/checkPermission'

const HomeDemoRoute = HomeDemoRouteImport.update({
  id: '/home-demo',
  path: '/home-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckPermissionRoute = LoginCheckPermissionRouteImport.update({
  id: '/login/checkPermission',
  path: '/login/checkPermission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home-demo': typeof HomeDemoRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-demo': typeof HomeDemoRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home-demo': typeof HomeDemoRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home-demo' | '/login/checkPermission' | '/landing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home-demo' | '/login/checkPermission' | '/landing'
  id: '__root__' | '/' | '/home-demo' | '/login/checkPermission' | '/landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeDemoRoute: typeof HomeDemoRoute
  LoginCheckPermissionRoute: typeof LoginCheckPermissionRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home-demo': {
      id: '/home-demo'
      path: '/home-demo'
      fullPath: '/home-demo'
      preLoaderRoute: typeof HomeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/checkPermission': {
      id: '/login/checkPermission'
      path: '/login/checkPermission'
      fullPath: '/login/checkPermission'
      preLoaderRoute: typeof LoginCheckPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeDemoRoute: HomeDemoRoute,
  LoginCheckPermissionRoute: LoginCheckPermissionRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
