/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as LoginCheckPermissionRouteImport } from './routes/login/checkPermission'
import { Route as LandingCafeRouteImport } from './routes/landing/cafe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckPermissionRoute = LoginCheckPermissionRouteImport.update({
  id: '/login/checkPermission',
  path: '/login/checkPermission',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingCafeRoute = LandingCafeRouteImport.update({
  id: '/landing/cafe',
  path: '/landing/cafe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing/cafe' | '/login/checkPermission' | '/landing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing/cafe' | '/login/checkPermission' | '/landing'
  id:
    | '__root__'
    | '/'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingCafeRoute: typeof LandingCafeRoute
  LoginCheckPermissionRoute: typeof LoginCheckPermissionRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/checkPermission': {
      id: '/login/checkPermission'
      path: '/login/checkPermission'
      fullPath: '/login/checkPermission'
      preLoaderRoute: typeof LoginCheckPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/cafe': {
      id: '/landing/cafe'
      path: '/landing/cafe'
      fullPath: '/landing/cafe'
      preLoaderRoute: typeof LandingCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingCafeRoute: LandingCafeRoute,
  LoginCheckPermissionRoute: LoginCheckPermissionRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
